const fs = require('fs');
const assert = require('assert');
const read = file => fs.readFileSync(file, 'utf8');
const pkg = JSON.parse(read('package.json'));
const version = read('src/app/appVersion.ts');
const view = read('src/presentation/importacao/ImportacaoTransacoesFinanceiroView.ts');
const estado = read('docs/governanca/04_ESTADO_ATUAL_OFICIAL.md');
const doc1187 = read('docs/importacao/CONFIRMACAO_HISTORICO_FINANCEIRO_1.18.7.md');
const doc1188 = read('docs/importacao/CONFIRMACAO_HISTORICO_FINANCEIRO_1.18.8.md');
const doc1189 = read('docs/importacao/CONFIRMACAO_HISTORICO_FINANCEIRO_1.19.3.md');
const perfilDom = read('src/presentation/perfil/PerfilDomView.ts');
const itemTpl = read('src/presentation/item/templates/ItemImportacaoTemplate.ts');
const perfilArquivo = read('src/domain/perfil/PerfilImportacaoArquivo.ts');

assert(pkg.version === '1.19.5');
assert(version.includes("APP_VERSION = '1.19.5'"));
assert(estado.includes('Versão atual deste pacote: 1.19.5'), 'estado atual não pode apontar versão velha');
assert(!estado.includes('Versão atual deste pacote: 1.16.0'), 'estado atual não pode contradizer a versão');
assert(doc1187.startsWith('# Confirmação Histórico Financeiro 1.18.7'), 'doc 1.18.7 não pode nascer com título 1.18.6');
assert(doc1189.includes('A primeira ação passa a ser “Ver o que aconteceu”'));
assert(doc1189.includes('Limpar restos e abrir revisão'));
assert(!view.includes('Conciliar staging'), 'UI principal não pode falar staging');
assert(!view.includes('Pré-visualizar e congelar pacote'), 'UI principal não pode falar pacote/congelar');
assert(view.includes('private readonly limiteRenderizacaoMobile = 80'), 'conciliação precisa ter limite mobile');
assert(view.includes('slice(0, this.limiteRenderizacaoMobile)'), 'conciliação não pode renderizar tudo');
assert(view.includes('data-conciliacao-limite-mobile'), 'usuária precisa saber que a lista foi limitada');
const recoveryMethod = view.slice(view.indexOf('private retomadaHumanaObrigatoriaView'), view.indexOf('private confirmacaoHistoricaView'));
assert(!recoveryMethod.includes('Faturamento protegido'), 'card de retomada não deve expor faturamento');
assert(!recoveryMethod.includes('Custo protegido'), 'card de retomada não deve expor custo');
assert(!recoveryMethod.includes('Lucro protegido'), 'card de retomada não deve expor lucro');
assert(recoveryMethod.includes('data-revisao-retomada-aberta'), 'revisão precisa abrir bloco real');
assert(recoveryMethod.includes('Ver o que aconteceu'), 'retomada precisa começar explicando antes de executar ação pesada');
assert(recoveryMethod.includes('Limpar restos e abrir revisão'), 'segunda ação deve ser explícita e honesta');
assert(view.includes('this.previaConfirmacao = result'), 'retomada deve abrir prévia protegida após limpeza');
assert(!perfilDom.includes('.xls,.xlsx'), 'importação de Perfil não deve oferecer Excel no accept');
assert(!itemTpl.includes('.xls,.xlsx'), 'importação de Item não deve oferecer Excel no accept');
assert(perfilArquivo.includes("'xls'") && perfilArquivo.includes("'xlsx'"), 'detecção de Excel deve continuar para mensagem humana');
console.log('auditoria-pre-relatorios-1188.test.cjs OK');
