const fs = require('fs');
const assert = require('assert');
const read = file => fs.readFileSync(file, 'utf8');
const pkg = JSON.parse(read('package.json'));
const version = read('src/app/appVersion.ts');
const useCase = read('src/application/importacao/ConfirmarImportacaoHistoricaFinanceiraUseCase.ts');
const view = read('src/presentation/importacao/ImportacaoTransacoesFinanceiroView.ts');
const doc = read('docs/aprovado-lider/desenvolvimento/transacoes-financeiras/importacao/regras/CONFIRMACAO_HISTORICO_FINANCEIRO_1.19.3.md');
assert.strictEqual(pkg.version, '1.19.5');
assert(version.includes("APP_VERSION = '1.19.5'"));
assert(useCase.includes("modo: 'previsualizar' | 'confirmar'"), 'confirmação definitiva deve exigir prévia');
assert(useCase.includes('previaId'), 'prévia deve ter identificador revalidável');
assert(useCase.includes('Recalcule a prévia antes de confirmar'), 'confirmar sem prévia atual deve bloquear');
assert(useCase.includes('valor pago exige aprovação de conciliação'), 'validado sozinho não basta para confirmar pagamento histórico');
assert(useCase.includes('valor pago não bate com a soma financeira vinculada'), 'use case deve revalidar soma do financeiro vinculado');
assert(useCase.includes('assinaturaTransacao'), 'deduplicação precisa considerar registro sem número');
assert(useCase.includes('sem-numero'), 'deduplicação de sem número deve existir');
assert(useCase.includes('rollbackConfirmacaoHistorica'), 'confirmação deve tentar rollback se falhar no meio');
assert(useCase.includes('movimentoFinanceiroId: mov.id'), 'pagamento deve guardar movimento financeiro vinculado');
assert(!useCase.includes('RegistrarMovimentacaoEstoqueUseCase'), 'histórico não baixa estoque/lote');
assert(view.includes('data-previsualizar-historico-financeiro'), 'UI deve ter prévia antes da confirmação');
assert(view.includes('data-previa-id'), 'UI deve confirmar usando a prévia visível');
assert(view.includes('Confirmar agora'), 'baixo clique: confirmação deve ser em lote com rótulo humano');
assert(view.includes('data-expandir-vinculos'), 'usuária deve poder expandir vínculos de uma vez');
assert(view.includes('data-recolher-vinculos'), 'usuária deve poder recolher vínculos de uma vez');
assert(!view.includes('slice(0, 20).map'), 'bloqueios não podem ser escondidos em só 20 itens');
assert(doc.includes('prévia obrigatória'));
assert(doc.includes('sem clique registro por registro'));
assert(doc.includes('não baixa estoque'));
console.log('confirmacao-historico-financeiro-1181 ok');
