const fs = require('fs');
const assert = require('assert');
const read = file => fs.readFileSync(file, 'utf8');
const pkg = JSON.parse(read('package.json'));
const version = read('src/app/appVersion.ts');
const useCase = read('src/application/importacao/ConfirmarImportacaoHistoricaFinanceiraUseCase.ts');
const view = read('src/presentation/importacao/ImportacaoTransacoesFinanceiroView.ts');
const resumo = read('src/application/financeiro/ResumoFinanceiroUseCase.ts');
const repo = read('src/infrastructure/repositories/ImportacaoStagingRepository.ts');
const domain = read('src/domain/importacao/ImportacaoTransacoesFinanceiro.ts');
const doc = read('docs/importacao/CONFIRMACAO_HISTORICO_FINANCEIRO_1.19.3.md');
assert.strictEqual(pkg.version, '1.19.5');
assert(version.includes("APP_VERSION = '1.19.5'"));
assert(useCase.includes("modo: 'previsualizar' | 'confirmar' | 'desfazer_lote'"), 'confirmação precisa permitir desfazer lote');
assert(useCase.includes('congelarPrevia'), 'prévia deve ser congelada no staging');
assert(useCase.includes('confirmacaoPreviaId'), 'staging deve guardar id da prévia congelada');
assert(useCase.includes('confirmacaoAssinatura'), 'staging deve guardar assinatura da prévia');
assert(useCase.includes('validarPreviaCongelada'), 'confirmação deve validar pacote congelado');
assert(useCase.includes('exigirRemocaoSegura'), 'deve bloquear confirmação sem rollback/desfazer seguro');
assert(useCase.includes('loteConfirmacaoId'), 'dado oficial precisa guardar lote de confirmação');
assert(useCase.includes('desfazerLote'), 'deve existir desfazer por lote');
assert(useCase.includes('bloqueiosExportacao'), 'bloqueios precisam ser exportáveis');
assert(view.includes('data-exportar-bloqueios-confirmacao'), 'UI deve exportar bloqueios completos');
assert(view.includes('data-corrigir-confirmacao-salva'), 'UI deve oferecer correção avançada de confirmação');
assert(view.includes('Ver antes de confirmar') && view.includes('revisão'), 'UI deve deixar claro em linguagem humana que existe revisão antes de confirmar');
assert(resumo.includes('ResumoFinanceiroFiltros'), 'resumo financeiro precisa aceitar filtros');
assert(resumo.includes('dataInicio') && resumo.includes('dataFim') && resumo.includes('perfil') && resumo.includes('metodo') && resumo.includes('statusFinanceiro'), 'filtros básicos devem existir');
assert(repo.includes('async remove'), 'repositório protegido de staging deve expor remoção quando necessário');
assert(domain.includes('confirmacaoPreviaId') && domain.includes('loteConfirmacaoId'), 'domínio do staging deve registrar prévia e lote');
assert(!useCase.includes('RegistrarMovimentacaoEstoqueUseCase'), 'histórico não baixa estoque/lote');
assert(doc.includes('corrigir confirmação já feita'));
assert(doc.includes('não muda o estoque'));
console.log('confirmacao-historico-financeiro-1182 ok');
