const fs = require('fs');
const assert = require('assert');
const read = file => fs.readFileSync(file, 'utf8');
const pkg = JSON.parse(read('package.json'));
const version = read('src/app/appVersion.ts');
const useCase = read('src/application/importacao/ConfirmarImportacaoHistoricaFinanceiraUseCase.ts');
const view = read('src/presentation/importacao/ImportacaoTransacoesFinanceiroView.ts');
const app = read('src/app/createKzeraAuthenticatedApp.ts');
const financeiroRepo = read('src/infrastructure/repositories/FinanceiroProtegidoRepository.ts');
const pacoteRepo = read('src/infrastructure/repositories/PacoteConfirmacaoHistoricaRepository.ts');
const resumo = read('src/application/financeiro/ResumoFinanceiroUseCase.ts');
const domain = read('src/domain/importacao/ImportacaoTransacoesFinanceiro.ts');
const doc = read('docs/importacao/CONFIRMACAO_HISTORICO_FINANCEIRO_1.19.3.md');
assert.strictEqual(pkg.version, '1.19.5');
assert(version.includes("APP_VERSION = '1.19.5'"));
assert(domain.includes('PacoteConfirmacaoHistorica'), 'domínio precisa ter pacote persistente de confirmação');
assert(useCase.includes('assinaturaPacoteDeItens'), 'pacote precisa ter assinatura própria');
assert(useCase.includes('duplicidade interna no próprio pacote'), 'duplicidade intra-lote deve bloquear');
assert(useCase.includes('movimentação financeira') && useCase.includes('já está vinculada em outro registro deste pacote'), 'financeiro repetido no mesmo lote deve bloquear');
assert(useCase.includes("status: 'falha_confirmacao'" ) || useCase.includes("'falha_confirmacao'"), 'falha parcial precisa ser persistida para recuperação');
assert(useCase.includes('recuperar_falha'), 'deve existir recuperação persistente de falha');
assert(useCase.includes('confirmacaoDesfazerTexto') && useCase.includes('DESFAZER'), 'desfazer lote precisa trava contra toque acidental');
assert(useCase.includes('alterado depois da confirmação'), 'desfazer deve bloquear dado mexido depois');
assert(view.includes('data-armar-confirmacao-historico'), 'confirmação grande precisa etapa de armar antes do toque final');
assert(view.includes('data-lotes-confirmados'), 'lotes confirmados devem aparecer após reload');
assert(view.includes('data-retomar-confirmacao-segura'), 'interrupções devem ser recuperáveis pela UI humana');
assert(view.includes('registros.slice().reverse()'), 'staging não pode esconder apenas últimas 8 linhas');
assert(app.includes('FinanceiroProtegidoRepository'), 'dados financeiros oficiais precisam usar repositório protegido no navegador');
assert(app.includes('PacoteConfirmacaoHistoricaRepository'), 'pacote persistente protegido precisa ser ligado no app');
assert(financeiroRepo.includes('payloadProtegido') && financeiroRepo.includes('financeiro-oficial'), 'repositório financeiro oficial deve proteger payload');
assert(pacoteRepo.includes('payloadProtegido') && pacoteRepo.includes('pacote-confirmacao-historica'), 'pacote deve ser protegido');
assert(resumo.includes('pagamentosPorTransacao') && resumo.includes('textoPagamentos'), 'filtro por método deve usar pagamentos, não só observação de movimento');
assert(resumo.includes('movimento.transacaoId ? idsFiltrados.has'), 'contagem de movimentos deve respeitar filtro de transação');
assert(!useCase.includes('RegistrarMovimentacaoEstoqueUseCase'), 'histórico não baixa estoque/lote');
assert(doc.includes('sem baixar estoque/lote'));
console.log('confirmacao-historico-financeiro-1183 ok');
