const fs = require('fs');
const assert = require('assert');
const read = file => fs.readFileSync(file, 'utf8');
const pkg = JSON.parse(read('package.json'));
const version = read('src/app/appVersion.ts');
const useCase = read('src/application/importacao/ConfirmarImportacaoHistoricaFinanceiraUseCase.ts');
const view = read('src/presentation/importacao/ImportacaoTransacoesFinanceiroView.ts');
const app = read('src/app/createKzeraAuthenticatedApp.ts');
const resumo = read('src/application/financeiro/ResumoFinanceiroUseCase.ts');
const doc = read('docs/importacao/CONFIRMACAO_HISTORICO_FINANCEIRO_1.19.3.md');
assert.strictEqual(pkg.version, '1.19.5');
assert(version.includes("APP_VERSION = '1.19.5'"));
assert(useCase.includes('ConfirmarImportacaoHistoricaFinanceiraUseCase'));
assert(useCase.includes('faturamentoTotal'));
assert(useCase.includes('custoTotal'));
assert(useCase.includes('lucroTotal'));
assert(useCase.includes('valorPendenteTotal'));
assert(useCase.includes('Histórico importado: não baixa estoque/lote.'));
assert(useCase.includes("valorPago > 0 && !financeirosResolvidos.length"), 'valor pago histórico exige financeiro vinculado');
assert(!useCase.includes('RegistrarMovimentacaoEstoqueUseCase'), 'histórico financeiro não pode depender de baixa de estoque');
assert(view.includes('data-confirmar-historico-financeiro'));
assert(view.includes('Ver valores financeiros') && view.includes('Faturamento') && view.includes('Custo') && view.includes('Lucro')); // valores ficam em detalhe avançado
assert(view.includes('Estoque não foi alterado') || view.includes('Estoque não será mexido')); 
assert(app.includes('new ConfirmarImportacaoHistoricaFinanceiraUseCase'));
assert(app.includes('renderTransacoesScreen'));
assert(app.includes('Resumo do dinheiro'));
assert(app.includes('O histórico importado entra no resumo do dinheiro. Ele não muda o estoque.'));
assert(resumo.includes('faturamento'));
assert(resumo.includes('custo'));
assert(resumo.includes('lucro'));
assert(doc.includes('não baixa estoque'));
assert(doc.includes('total/faturamento'));
assert(doc.includes('custo'));
assert(doc.includes('lucro'));
console.log('confirmacao-historico-financeiro-1180 ok');
