const fs = require('fs');
const assert = require('assert');
const read = file => fs.readFileSync(file, 'utf8');
const pkg = JSON.parse(read('package.json'));
const version = read('src/app/appVersion.ts');
const useCase = read('src/application/importacao/ConfirmarImportacaoHistoricaFinanceiraUseCase.ts');
const listar = read('src/application/importacao/ListarStagingImportacaoUseCase.ts');
const view = read('src/presentation/importacao/ImportacaoTransacoesFinanceiroView.ts');
const app = read('src/app/createKzeraAuthenticatedApp.ts');
const doc = read('docs/importacao/CONFIRMACAO_HISTORICO_FINANCEIRO_1.19.3.md');
assert.strictEqual(pkg.version, '1.19.5');
assert(version.includes("APP_VERSION = '1.19.5'"));
assert(useCase.includes('reconsultarStagingAtualAntesDeConfirmar'), 'confirmação deve reconsultar staging atual antes do pacote antigo');
assert(useCase.includes('snapshotTransacaoComparavel') && useCase.includes('snapshotFinanceiroComparavel'), 'snapshots atuais precisam bloquear alterações pós-prévia');
assert(useCase.includes('assinaturaTransacaoOficial'), 'deduplicação precisa reconstruir assinatura de oficiais antigos');
assert(useCase.includes("pacote.status === 'confirmando'"), 'pacote confirmando deve ser recuperável/listado');
assert(useCase.includes('atualizarPacoteAntesDoArtefato'), 'artefato oficial deve ser registrado antes do write oficial');
assert(useCase.includes('const planoFinal = this.planoDoPacote(pacoteFinal)'), 'resultado final deve vir do pacote congelado');
assert(listar.includes('limiteVisualizacao = 80') && listar.includes('slice(-limiteVisualizacao)'), 'staging não pode renderizar lista gigante');
assert(view.includes('release(): void') && view.includes('releaseObject(this.previaConfirmacao)') && view.includes("this.root.innerHTML = ''"), 'view deve limpar memória/DOM no bloqueio');
assert(app.includes('security.resourceScope.register(importacaoTransacoesFinanceiroApp)') && app.includes('bloquear.execute(); return;'), 'view de importação precisa entrar no ciclo de limpeza no app hidden/bloqueio');
assert(doc.includes('A versão 1.18.4 não passa') && doc.includes('não baixa estoque'));
console.log('confirmacao-historico-financeiro-1185 ok');
