const fs = require('fs');
const assert = require('assert');
const read = file => fs.readFileSync(file, 'utf8');
const pkg = JSON.parse(read('package.json'));
const version = read('src/app/appVersion.ts');
const repo = read('src/infrastructure/repositories/PacoteConfirmacaoHistoricaRepository.ts');
const domain = read('src/domain/importacao/ImportacaoTransacoesFinanceiro.ts');
const useCase = read('src/application/importacao/ConfirmarImportacaoHistoricaFinanceiraUseCase.ts');
const doc = read('docs/importacao/CONFIRMACAO_HISTORICO_FINANCEIRO_1.19.3.md');
assert.strictEqual(pkg.version, '1.19.5');
assert(version.includes("APP_VERSION = '1.19.5'"));
assert(domain.includes('ResumoProtegidoPacoteConfirmacaoHistorica'), 'resumo financeiro do pacote precisa ter contrato protegido');
assert(repo.includes('resumoProtegido(pacote)'), 'repositório deve mover totais financeiros para payload protegido');
const toRecordBody = repo.match(/function toRecord[\s\S]*?return record;\n}/)?.[0] || '';
assert(!toRecordBody.includes('faturamentoTotal'), 'registro aberto do pacote não deve persistir faturamento em claro');
assert(!toRecordBody.includes('custoTotal'), 'registro aberto do pacote não deve persistir custo em claro');
assert(!toRecordBody.includes('lucroTotal'), 'registro aberto do pacote não deve persistir lucro em claro');
assert(repo.includes('payloadProtegido') && repo.includes('packJson'), 'pacote deve ser criptografado antes de persistir resumo financeiro');
assert(useCase.includes('stableStringify'), 'assinatura do pacote deve cobrir snapshot completo ordenado');
assert(useCase.includes('stagingSnapshot: item.stagingSnapshot') && useCase.includes('financeirosSnapshot: item.financeirosSnapshot'), 'assinatura deve detectar alteração de snapshot inteiro');
assert(doc.includes('resumo financeiro dentro do payload protegido'));
assert(doc.includes('não baixa estoque'));
console.log('confirmacao-historico-financeiro-1184 ok');
