const assert = require('assert');
const fs = require('fs');
const read = file => fs.readFileSync(file, 'utf8');
const pkg = JSON.parse(read('package.json'));
const version = read('src/app/appVersion.ts');
const app = read('src/app/createKzeraAuthenticatedApp.ts');
const backup = read('src/application/backup/BackupExportUseCase.ts');
const numberParser = read('src/presentation/shared/ui/NumberParser.ts');
const pesagemUseCase = read('src/application/item/PesagemRapidaFracionamentoUseCase.ts');
const pesagemDomain = read('src/domain/operacao/PesagemRapida.ts');
const loteRenderer = read('src/presentation/item/renderers/LoteOperacionalRenderer.ts');
const itemApp = read('src/app/createItemCatalogoUiApp.ts');
const css = read('public/styles.css');
const doc = read('docs/CORRECOES_PRE_TRANSACOES_1.13.3.md');
const estado = read('docs/governanca/04_ESTADO_ATUAL_OFICIAL.md');
assert.strictEqual(pkg.version, '1.19.5', 'Versão deve ser 1.15.1.');
assert(version.includes("APP_VERSION = '1.19.5'"), 'APP_VERSION deve estar em 1.15.1.');
assert(app.includes('PerfilRepository'), 'Perfis devem usar repositório seguro no app principal.');
assert(app.includes('scheduleBackupCheck'), 'Backup obrigatório deve ter verificação periódica.');
assert(backup.includes('balancas?: unknown[]'), 'Backup deve aceitar balanças/calibragens.');
assert(app.includes('balancas: await balancas.list()'), 'Backup do app deve incluir balanças.');
assert(numberParser.includes('replace(\',\', \'.\')'), 'Parser operacional deve aceitar vírgula decimal.');
assert(itemApp.includes("status: loteAtivo ? 'ativo' : 'encerrado'"), 'Lote zero não deve nascer ativo.');
assert(pesagemDomain.includes('divergenciaRegistrosFracionamento'), 'Domínio deve calcular divergência entre pesagem e fracionamento.');
assert(pesagemUseCase.includes('podeRegistrarPesoNaSessao'), 'Use case deve impedir pesagem acima das unidades fracionadas.');
assert(loteRenderer.includes('Progresso:'), 'UI da pesagem deve mostrar progresso.');
assert(loteRenderer.includes('pesagem-correcao-form'), 'UI deve permitir correção individual de peso.');
assert(css.includes('modo operação noturna'), 'CSS deve registrar modo operação noturna.');
assert(doc.includes('política de senha forte fica para a fase final'), 'Documento deve registrar senha forte por último.');
assert(estado.includes('Senha forte'), 'Estado atual deve registrar decisão sobre senha forte.');
assert(pkg.scripts.test.includes('pre-transacoes-operacao-noturna-1133.test.cjs'), 'npm test deve incluir 1.15.1.');
assert.strictEqual(pkg.scripts.test, pkg.scripts.check, 'npm test e npm check devem continuar iguais.');
console.log('pre-transacoes-operacao-noturna-1133.test.cjs OK');
